openapi: 3.0.3
info:
  title: Open Customer Data Api
  description: Open Customer Data Api
  version: 1.2.0
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'localhost:8080/test-api'
    description: Development server
tags:
  - name: Consents
    description: Operation to create and get consents
  - name: Accounts
    description: Operation to get Account information
paths:
  '/consents/v1/consents':
    post:
      tags:
        - Consents
      summary: Create a consent
      description: Create a consent
      operationId: postConsent
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConsent'
        description: Payload para criação do consentimento.
        required: true
      responses:
        '200':
          $ref: '#/components/responses/OKResponsePersonalCustomersIdentificationV2'
  '/consents/v1/consents/{consentId}':
    put:
      tags:
        - Consents
      summary: Update a consent
      description: Update a consent
      operationId: putConsent
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/ConsentId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConsent'
        description: Payload para criação do consentimento.
        required: true
      responses:
        '200':
          $ref: '#/components/responses/OKResponsePersonalCustomersIdentificationV2'
    get:
      tags:
        - Consents
      summary: Get consent
      description: Get consent
      operationId: getConsent
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/ConsentId'
      responses:
        '200':
          $ref: '#/components/responses/OKResponsePersonalCustomersIdentificationV2'
  '/accounts/v1/accounts':
    get:
      tags:
        - Accounts
      summary: Obtém os registros de identificação da pessoa natural.
      description: Método para obter os registros de identificação da pessoa natural mantidos na instituição transmissora.
      operationId: customersGetPersonalIdentificationsV2
      parameters:
        - $ref: '#/components/parameters/Authorization'
      responses:
        '200':
          $ref: '#/components/responses/OKResponsePersonalCustomersIdentificationV2'
  '/accounts/v1/accounts/{accountId}':
    get:
      tags:
        - Accounts
      summary: Obtém os registros de identificação da pessoa natural.
      description: Método para obter os registros de identificação da pessoa natural mantidos na instituição transmissora.
      operationId: customersGetPersonalIdentificationsV2
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/ConsentId'
      responses:
        '200':
          $ref: '#/components/responses/OKResponsePersonalCustomersIdentificationV2'
components:
  parameters:
    Authorization:
      name: Authorization
      in: header
      description: | 
        Cabeçalho HTTP padrão. Permite que as credenciais sejam fornecidas dependendo do tipo de recurso solicitado
      required: true
      schema:
        type: string
        pattern: '[\w\W\s]*'
        maxLength: 2048
    ConsentId:
      name: consentId
      in: path
      description: Cabeçalho HTTP padrão. Permite que as credenciais sejam fornecidas dependendo do tipo de recurso solicitado
      required: true
      schema:
        type: string
        pattern: '[\w\W\s]*'
        maxLength: 2048
    AccountId:
      name: accountId
      in: path
      description: Cabeçalho HTTP padrão. Permite que as credenciais sejam fornecidas dependendo do tipo de recurso solicitado
      required: true
      schema:
        type: string
        pattern: '[\w\W\s]*'
        maxLength: 2048
  schemas:
    CreateConsent:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/CreateConsentData'
    CreateConsentData:
      type: object
      description: Utilizado para informar para qual estado deve ir o pagamento. Atualmente o único valor possível é CANC.
      required:
        - permissions
        - expirationDateTime
      properties:
        permissions:
          type: string
          enum:
            - ACCOUNTS_READ
            - CREDIT_CARD_READ
          description: |
            O preenchimento desse campo para retorno, deve ocorrer pela detentora de contas a partir do status em que o pagamento estiver no momento da solicitação do cancelamento (ex. Status de pagamento = PDNG, campo deve ser preenchido com enum CANCELADO_PENDENCIA)
            Valores possíveis:
            - ACCOUNTS_READ - Pagamento cancelado enquanto estava na situação PDNG
            - CREDIT_CARD_READ - Pagamento cancelado enquanto estava na situação SCHD
        expirationDateTime:
          type: date-time
    UpdateConsent:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/UpdateConsentData'
    UpdateConsentData:
      type: object
      description: Utilizado para informar para qual estado deve ir o pagamento. Atualmente o único valor possível é CANC.
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - AWAITING_AUTHORISATION
            - AUTHORISED
            - REJECTED
          description: |
            O preenchimento desse campo para retorno, deve ocorrer pela detentora de contas a partir do status em que o pagamento estiver no momento da solicitação do cancelamento (ex. Status de pagamento = PDNG, campo deve ser preenchido com enum CANCELADO_PENDENCIA)
            Valores possíveis:
            - AWAITING_AUTHORISATION - Pagamento cancelado enquanto estava na situação PDNG
            - AUTHORISED - Pagamento cancelado enquanto estava na situação SCHD
            - REJECTED - Pagamento cancelado enquanto estava na situação SCHD
